cabal-version:  2.4
name:           text-templates
version:        0.1.0.0
license:        BSD-3-Clause
license-file:   LICENSE.md
maintainer:     Harley Eades III <harley.eades@gmail.com>
author:         Harley Eades III

tested-with: 
    ghc ==9.10.3

homepage:       https://github.com/heades/text-templates
bug-reports:    https://github.com/heades/text-templates/issues
synopsis:       Add, fill, plug holes in text
description:    
    In its simplest form, this is a text interpolation library, but
    with the ability to allow a custom language to fill or plug the  
    placeholders we call "holes".

category:       Text
build-type:     Simple
extra-source-files:
    README.md
    CHANGELOG.md

source-repository head
  type: git
  location: https://github.com/heades/text-templates

common depends
    build-depends:
       base             >= 4.7    && < 5    
      ,constraints      >= 0.14.4 && < 0.15
      ,containers       >= 0.7    && < 0.8
      ,extra            >= 1.8.1  && < 1.9
      ,megaparsec       >= 9.7.0  && < 9.9
      ,mtl              >= 2.3.1  && < 2.4
      ,template-haskell >= 2.22.0 && < 2.24
      ,text             >= 2.1.3  && < 2.2
      ,type-natural     >= 1.3.0  && < 1.4

common test-depends
    build-depends:
       HUnit                >= 1.6.2   && < 1.7
      ,QuickCheck           >  2.15.0  && < 2.19
      ,hspec                >= 2.11.17 && < 2.12
      ,hspec-contrib        >= 0.5.2   && < 0.6
      ,quickcheck-instances >= 0.3.33  && < 0.5

library
  import: depends
  exposed-modules:
      Data.TextTemplate
      Data.TextTemplate.TemplateInternal
      Data.TextTemplate.QQInternal
      Data.TextTemplate.Text
      Data.TextTemplate.JSON
      Data.TextTemplate.JSONInternal
      Data.NatMap
  other-modules:
      Paths_text_templates      
  autogen-modules:
      Paths_text_templates
  hs-source-dirs:
      src
  ghc-options: -Wall 
               -Wcompat 
               -Widentities 
               -Wincomplete-record-updates 
               -Wincomplete-uni-patterns 
               -Wmissing-export-lists 
               -Wmissing-home-modules 
               -Wpartial-fields 
               -Wredundant-constraints
               -Wno-name-shadowing 
  default-extensions:     
    ImportQualifiedPost
    OverloadedStrings
    InstanceSigs
    LambdaCase
    ViewPatterns
    PatternSynonyms
    GADTs
  default-language: Haskell2010

test-suite text-templates-test
  import: depends, test-depends
  type: exitcode-stdio-1.0
  main-is: Spec.hs
  other-modules:
      Paths_text_templates
      Data.TextTemplate.TemplateInternalSpec
      Data.TextTemplate.QQInternalSpec      
      Data.TextTemplate.JSONInternalSpec
      Test.QuickCheck.TextTemplate
      Test.Helpers
  autogen-modules:
      Paths_text_templates
  hs-source-dirs:
      test
  ghc-options: -Wall -Wcompat -Widentities -Wincomplete-record-updates -Wincomplete-uni-patterns -Wmissing-export-lists -Wmissing-home-modules -Wpartial-fields -Wredundant-constraints -threaded -rtsopts -with-rtsopts=-N
  default-extensions: 
    ImportQualifiedPost
    OverloadedStrings
    InstanceSigs
    LambdaCase
    ViewPatterns
    GADTs
  build-depends:     
    ,text-templates    
  default-language: Haskell2010
